Tacticode.maps.sample = {
    name: 'Sample map',
    style: 'basic',
    x: 5,
    y: 5,
    cells: [
        {x: 0, y: 0, tile: 'GROUND', accessible: true, los: true},
        {x: 0, y: 1, tile: 'GROUND', accessible: true, los: true},
        {x: 0, y: 2, tile: 'GROUND', accessible: true, los: true},
        {x: 0, y: 3, tile: 'GROUND', accessible: true, los: true},
        {x: 0, y: 4, tile: 'GROUND', accessible: true, los: true},
        {x: 1, y: 0, tile: 'GROUND', accessible: true, los: true},
        {x: 1, y: 1, tile: 'GROUND', accessible: true, los: true},
        {x: 1, y: 2, tile: 'GROUND', accessible: true, los: true},
        {x: 1, y: 3, tile: 'GROUND', accessible: true, los: true},
        {x: 1, y: 4, tile: 'GROUND', accessible: true, los: true},
        {x: 2, y: 0, tile: 'GROUND', accessible: true, los: true},
        {x: 2, y: 1, z: 1 , tile: 'TREE', accessible: false, los: false},
        {x: 2, y: 2, tile: 'GROUND', accessible: true, los: true},
        {x: 2, y: 3, tile: 'GROUND', accessible: true, los: true},
        {x: 2, y: 4, tile: 'GROUND', accessible: true, los: true},
        {x: 3, y: 0, tile: 'GROUND', accessible: true, los: true},
        {x: 3, y: 1, tile: 'GROUND', accessible: true, los: true},
        {x: 3, y: 2, tile: 'GROUND', accessible: true, los: true},
        {x: 3, y: 3, tile: 'GROUND', accessible: true, los: true},
        {x: 3, y: 4, tile: 'GROUND', accessible: true, los: true},
        {x: 4, y: 0, tile: 'GROUND', accessible: true, los: true},
        {x: 4, y: 1, tile: 'GROUND', accessible: true, los: true},
        {x: 4, y: 2, tile: 'GROUND', accessible: true, los: true},
        {x: 4, y: 3, z: 1, tile: 'TREE', accessible: true, los: true},
        {x: 4, y: 4, tile: 'GROUND', accessible: true, los: true}
    ]
}
